ifneq (,$(filter vaina,$(USEMODULE)))
  USEMODULE += sock_udp
  USEMODULE += turpial_firmware_net
endif

ifneq (,$(filter tfsettings,$(USEMODULE)))
  USEMODULE += tfstorage
  USEMODULE += tfnvs
  USEMODULE += nvs
  USEMODULE += sock_udp
endif

ifneq (,$(filter tfnvs,$(USEMODULE)))
  USEMODULE += tfstorage
  USEMODULE += esp_idf_nvs_flash
endif

ifneq (,$(filter tfcoap,$(USEMODULE)))
  USEMODULE += tfnet
  USEMODULE += gcoap
  USEMODULE += cjson
endif
