ifneq (,$(filter vaina,$(USEMODULE)))
  USEMODULE += sock_udp
  USEMODULE += turpial_firmware_net
  USEMODULE += turpial_firmware_storage
  USEMODULE += esp_idf_nvs_flash
endif

ifneq (,$(filter nvs,$(USEMODULE)))
  USEMODULE += turpial_firmware_storage
  USEMODULE += esp_idf_nvs_flash
endif


ifneq (,$(filter wifi_settings,$(USEMODULE)))
  USEMODULE += turpial_firmware_storage
  USEMODULE += nvs
  USEMODULE += sock_udp
endif