MODULE = turpial_core

ifneq (,$(filter cjson,$(USEMODULE)))
  DIRS += contrib/cjson
endif

ifneq (,$(filter oonf_api,$(USEMODULE)))
  DIRS += contrib/oonf_api
endif

include $(RIOTBASE)/Makefile.base
