name: Automated tests

on: [push, pull_request]

jobs:
    codespell:
        name: Check for spelling errors
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: codespell-project/actions-codespell@master
              with:
                  check_filenames: false
                  check_hidden: false
                  skip: RIOT,*.svg,./sys/oonf_api,.git
                  ignore_words_list: rsource,inout
