name: Codespell

on: [push, pull_request]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: codespell-project/actions-codespell@master
        with:
            check_filenames: false
            check_hidden: false
            skip: RIOT,*.svg,./core/contrib,.git
            # ignore_words_list: rsource,inout,doubleclick,crate,rsource,bufffer,trucated,calculate,childs,elments,continous,neigbor,Initalize,initalize,happend,inout
            ignore_words_file: .dist/codespell/ignored_words.txt
            only_warn: 1