dist: bionic

before_script:
 - wget "https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2"
 - tar xvf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
 - export PATH=$PWD/gcc-arm-none-eabi-9-2019-q4-major/bin/:$PATH

script:
 - make
